Docker
chefbe-dot-net/attitude pull request #5
Opened 2021-10-30 12:55 UTC by ciremoussadia

2021-10-30 12:59 UTC, ciremoussadia commented
@blambeau We just need to add env vars and it's good to go.
Envs to add SLACK_WEBHOOK_URL, DOCKER_HUB_USERNAME & DOCKER_HUB_ACCESS_TOKEN

2021-10-30 14:35 UTC, blambeau commented
I can't do the review right now, please keep the klaro card open (and
under your responsibility) on your side (you can add a "blocked" status
if needed in Klaro).

B

On October 30, 2021, GitHub ***@***.***> wrote:
> @blambeau <https://github.com/blambeau> We just need to add env vars
> and it's good to go.
>  Envs to add SLACK_WEBHOOK_URL, DOCKER_HUB_USERNAME &
> DOCKER_HUB_ACCESS_TOKEN
>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/chefbe-dot-net/attitude/pull/5#issuecomment-
955205471>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AAAN4ZTXETNCXCCHEXWG3CTUJPT3HANCNFSM5HBBZYTQ>.

2021-11-09 11:43 UTC, llambeau commented on .github/workflows/release.yml
> +  Tests:
Rename this

2021-11-09 11:53 UTC, blambeau requested changes
Make sure tests are executed before push.
Can be merged as soon as the build is green.

2021-11-16 07:07 UTC, merged